#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "schemas" / "clinical-vocabulary.source.json"
MODELS = ROOT / "production_ready_pipeline" / "nccn_input" / "models"
JSON_OUTPUT = ROOT / "schemas" / "clinical-vocabulary.json"
JS_OUTPUT = ROOT / "js" / "clinical-vocabulary.js"
PY_OUTPUT = ROOT / "production_ready_pipeline" / "generated_clinical_vocabulary.py"

CANCER_LABELS = {
    "bladder_urothelial": "Bladder",
    "prostate": "Prostate",
    "kidney": "Kidney",
    "testicular": "Testicular",
}


def token(value: Any) -> str:
    return re.sub(r"[^a-z0-9+]+", "_", str(value or "").strip().lower()).strip("_")


def canonical_axis_value(source: dict[str, Any], axis: str, value: Any) -> str:
    value_token = token(value)
    return source.get("axisValueAliases", {}).get(axis, {}).get(
        value_token,
        source.get("globalAliases", {}).get(value_token, value_token),
    )


def build() -> dict[str, Any]:
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    vocabulary: dict[str, Any] = {
        key: value for key, value in source.items() if key != "seedClinicalAxes"
    }
    vocabulary["diseaseSettings"] = {}
    vocabulary["clinicalAxes"] = json.loads(json.dumps(source.get("seedClinicalAxes", {})))
    vocabulary["taxonomyVersions"] = {}

    for model_path in sorted(MODELS.glob("*.json")):
        taxonomy = json.loads(model_path.read_text(encoding="utf-8"))
        cancer = CANCER_LABELS.get(token(taxonomy.get("disease")))
        if not cancer:
            continue
        vocabulary["diseaseSettings"][cancer] = sorted({
            token(category.get("id"))
            for category in taxonomy.get("categories", [])
            if category.get("id")
        })
        vocabulary["taxonomyVersions"][cancer] = {
            "version": taxonomy.get("nccn_version", ""),
            "date": taxonomy.get("nccn_date", ""),
            "sourceFile": model_path.name,
        }
        axes = vocabulary["clinicalAxes"].setdefault(cancer, {})
        for axis, definition in (taxonomy.get("clinical_axes") or {}).items():
            values = {
                canonical_axis_value(source, axis, value)
                for value in definition.get("values", [])
                if token(value) not in {"", "not_applicable"}
            }
            values.add("unknown")
            axes[axis] = sorted(values)

    for cancer, axes in vocabulary["clinicalAxes"].items():
        for axis, values in axes.items():
            axes[axis] = sorted({canonical_axis_value(source, axis, value) for value in values})
    return vocabulary


def write_outputs(vocabulary: dict[str, Any]) -> None:
    serialized = json.dumps(vocabulary, ensure_ascii=False, indent=2, sort_keys=True)
    JSON_OUTPUT.write_text(serialized + "\n", encoding="utf-8")
    compact = json.dumps(vocabulary, ensure_ascii=False, separators=(",", ":"))
    JS_OUTPUT.write_text(
        "(function (global) {\n"
        "  \"use strict\";\n"
        f"  const vocabulary = Object.freeze({compact});\n"
        "  global.ClinicalVocabulary = vocabulary;\n"
        "  if (typeof module !== \"undefined\" && module.exports) module.exports = vocabulary;\n"
        "})(typeof window !== \"undefined\" ? window : globalThis);\n",
        encoding="utf-8",
    )
    PY_OUTPUT.write_text(
        "# Generated by build_clinical_vocabulary.py. Do not edit by hand.\n"
        "from __future__ import annotations\n\n"
        f"CLINICAL_VOCABULARY = {repr(vocabulary)}\n"
        "SCHEMA_VERSION = CLINICAL_VOCABULARY['schemaVersion']\n"
        "DISEASE_SETTINGS = CLINICAL_VOCABULARY['diseaseSettings']\n"
        "CLINICAL_AXES = CLINICAL_VOCABULARY['clinicalAxes']\n",
        encoding="utf-8",
    )


def main() -> int:
    vocabulary = build()
    write_outputs(vocabulary)
    print(json.dumps({
        "schemaVersion": vocabulary["schemaVersion"],
        "diseaseSettingCount": sum(len(values) for values in vocabulary["diseaseSettings"].values()),
        "axisCount": sum(len(values) for values in vocabulary["clinicalAxes"].values()),
        "outputs": [str(JSON_OUTPUT), str(JS_OUTPUT), str(PY_OUTPUT)],
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
